apiVersion: v1
kind: Service
metadata:
  name: usermanagement
  namespace: usermanagement
  labels:
    app: usermanagement
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 8082
    targetPort: 8080
  selector:
    app: usermanagement