apiVersion: v1
kind: Service
metadata:
  name: user_management
  namespace: usermanagement
  labels:
    app: user_management
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 8080
  selector:
    app: user_management