apiVersion: v1
kind: Service
metadata:
  name: usermanagement
  namespace: usermanagement
  labels:
    app: usermanagement
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 80
    targetPort: 8081
  selector:
    app: usermanagement