apiVersion: v1
kind: Service
metadata:
  name: usermanagement
  namespace: usermanagement
  labels:
    app: usermanagement
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 8080
    targetPort: 8082
  selector:
    app: usermanagement