image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: Build
          script:
            - ./mvnw verify --file pom.xml
          caches:
            - maven
          after-script:
            #- pipe: atlassian/checkstyle-report:0.3.0
              variables:
                DEBUG: "true"
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1

  branches:
    user-dev:
      - step:
          name: Build
          script:
            - ./mvnw package -DskipTests
            - zip -j application.zip target/hello-world-0.0.1-SNAPSHOT.jar
          artifacts:
            - application.zip
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
