stages:
    - build
    - deploy

build:
    stage: build
    script:
        - echo "Building app..."
        - ./mvnw clean install
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
            - home/usermanagement
    only:
        - user-dev
