stages:
    - build
    - deploy

build:
    stage: build
    image:  maven:3.6.1-jdk-8-slim
    script:
        - echo "Building app..."
        - export PATH=/usr/share/maven
        - export PATH=/usr/share/java
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
            - target/consoleapp.jar
    only:
        - user-dev

deploy:
    stage: deploy
    image: docker:latest
    before_script:
        - apk add --update python-pip
        - pip install docker-compose
        - which ssh-agent || ( apk update && apk add openssh-client )
        - eval $(ssh-agent -s)
        - ssh-keygen -p -m PEM -f cat ~/.ssh/id_rsa.pub
        #- ssh-add <(echo -e "$SSH_PRIVATE_KEY")
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    script:
        - echo "Deploying started..."
        - scp -o StrictHostKeyChecking=no -i ${SSH_PRIVATE_KEY} ubuntu@${DEV_SERVER_IP}:/home/ubuntu
        - ssh -o StrictHostKeyChecking=no -i ${SSH_PRIVATE_KEY} ubuntu@${DEV_SERVER_IP}"
        - scp ./target/consoleapp.jar ubuntu@$DEPLOY_SERVER_IP:~/console-app/
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start consoleapp.service"
        - echo "Finished deploying the app."
    only:
        - user-dev

