variables:
  AWS_ACCESS_KEY_ID: <your_aws_access_key_id>
  AWS_SECRET_ACCESS_KEY: <your_aws_secret_access_key>
  AWS_DEFAULT_REGION: <your_aws_region>
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

stages:
  - build
  - deploy

build:
  image: maven:3-jdk-11
  stage: build
  script:
    - mvn package -DskipTests

deploy:
  image: python:latest
  stage: deploy
  script:
    - apt-get update && apt-get install -y awscli
    - aws ec2 run-instances --image-id ami-0c55b159cbfafe1f0 --count 1 --instance-type t2.micro --key-name my-key-pair --security-group-ids sg-0b5f41d8923cb7f3b --subnet-id subnet-0f5b611efeb080a77 || true
  only:
    - user-dev
  when: on_success
