stages:
    - build
    - deploy

build:
    image: maven:3.6.0-jdk-8-slim
    stage: build
    script:
        - mvn clean install -Dmaven.test.skip=true

    artifacts:
        #expire_in: 1 week
        paths:
            - archivist/target/*.jar
            - elasticsearch/*.zip
    only:
        - user-dev


