stages:
    - build
    - deploy

build:
    stage: build
    image: maven:latest
    script:
        - ./mvnw install
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
            - home/gitlab-runner
    only:
        - user-dev
