stages:
    - build
    - deploy

build:
    stage: build
    image:  maven:default
    script:
        - echo "Building app..."
        - mvn clean install
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
            - target/consoleapp.jar
    only:
        - user-dev
