stages:
    - build
    - deploy

build:
    stage: build
    image: maven:3-jdk-9
    script:
        - echo "Building app..."
        - ./mvnw -U clean install
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
            - export JAVA_HOME="`/usr/libexec/java_home`"
    only:
        - user-dev
