stages:
    - build
    - deploy

build:
    stage: build
    image:  maven:3.5-jdk-8-alpine
    script: "mvn package -B"

    artifacts:
        #expire_in: 1 week
        paths:
            - export JAVA_HOME=/opt/java/openjdk
    only:
        - user-dev


