stages:
    - build
    - deploy

build:
    stage: build
    image: maven:latest
    script:
        - echo "Building app..."
        - ./mvnw clean install
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
           - /usr/bin/java
    only:
        - user-dev
