stages:
    - build
build:
    stage: build
    image:  maven:3.6.1-jdk-8-slim
    script:
        - echo "Building app..."
        - ./mvnw install
        - echo "Finished building the app."
    only:
        - akanshu-deploy
