stages:
    - build
    - deploy

build:
    stage: build
    image: maven:latest
    script:
        - echo "Building app..."
        - ./mvnw clean install
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
        - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
    only:
        - user-dev
