stages:
    - build
    - deploy

build:
    stage: build
    image:  maven:3.6.1-jdk-8-slim
    script:
        - echo "Building app..."
        - cd src
        - ./mvnw install
        - echo "Finished building the app."
