stages:
  - build
  - deploy

build:
  stage: build
  image: gradle:jdk
  script:
    - gradle build
  artifacts:
    paths:
      - my_app.jar

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt-get update
    - apt-get -y install openssh-client
    - scp my_app.jar target.server:/my_app.jar
only:
    - user-dev


