image: docker:19.03.12

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: "1.0"
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:19.03.12-dind

stages:          # List of stages for jobs, and their order of execution
  - build_image
  - deploy_arrivnow-dev
  # - deploy_arrivnow-sales-demo

docker-build-image:
  stage: build_image
  tags:
    - docker
    - java
  script:
    - docker info
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME:$IMAGE_TAG
  when: always
  only: 
    - user-dev

deploy_to_dev:
  stage: deploy_arrivnow-dev
  tags:
    - docker
    - java
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@3.7.138.38 "
     docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
     docker run -d -p 8081:8081 $IMAGE_NAME:$IMAGE_TAG"
  only: 
    - user-dev
