stages:
  - build
  - deploy
  
build:
  stage: build
  image: openjdk:12-alpine
  script:
    - ./gradlew build
    -  mv ./build/libs/AWS-0.0.1-SNAPSHOT.jar ./build/libs/$ARTIFACT_NAME
  artifacts:
    paths:
    - ./build/libs/


