variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: "1.0"
stages:
    - build
    - push
build_image:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
