stages:
    - build
build:
    stage: build
    image: maven:3.6.3-jdk-8 
    script:
        - echo "Building app..."
        - ./mvnw install
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
            - home/gitlab-runner/
    only:
        - user-dev
