stages:
    - build
    - deploy

build:
    stage: build
    image:  3.9.0-eclipse-temurin-19-focal
    script:
        - echo "Building app..."
        - ./mvnw install
        - export PATH=/usr/share/maven
        - export PATH=/usr/share/java
        - echo "Finished building the app."
    artifacts:
        #expire_in: 1 week
        paths:
            - home/gitlab-runner
    only:
        - user-dev
